<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <ProjectReference Include="..\Prognode.Contracts\Prognode.Contracts.csproj" />
    <ProjectReference Include="..\Prognode.Core\Prognode.Core.csproj" />
    <ProjectReference Include="..\Prognode.Licensing\Prognode.Licensing.csproj" />
  </ItemGroup>
</Project>
