<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Prognode.Data/Prognode.Data.csproj" />
    <ProjectReference Include="../../src/Prognode.Licensing/Prognode.Licensing.csproj" />
  </ItemGroup>
</Project>
