<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Prognode.Contracts\Prognode.Contracts.csproj" />
    <ProjectReference Include="..\Prognode.Core\Prognode.Core.csproj" />
    <ProjectReference Include="..\Prognode.Alarm\Prognode.Alarm.csproj" />
    <ProjectReference Include="..\Prognode.Trends\Prognode.Trends.csproj" />
    <ProjectReference Include="..\Prognode.Historian\Prognode.Historian.csproj" />

    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
  </ItemGroup>
</Project>
