<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <ProjectReference Include="..\Prognode.Contracts\Prognode.Contracts.csproj" />
    <ProjectReference Include="..\Prognode.Protocols.Abstractions\Prognode.Protocols.Abstractions.csproj" />
  </ItemGroup>
</Project>
